CREATE DATABASE IF NOT EXISTS WEATHER_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS WEATHER_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS WEATHER_ANALYTICS.STAGING;
CREATE SCHEMA IF NOT EXISTS WEATHER_ANALYTICS.MARTS;

USE DATABASE WEATHER_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT RAW.JSON_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = FALSE;

CREATE OR REPLACE TABLE RAW.WEATHER_OBSERVATIONS (
    raw_data VARIANT,
    source_file STRING,
    loaded_at TIMESTAMP_NTZ
);

CREATE OR REPLACE STAGE RAW.WEATHER_S3_STAGE
    URL = 's3://YOUR_BUCKET_NAME/weather/raw/'
    CREDENTIALS = (
        AWS_KEY_ID = 'AWS_ACCESS_KEY_ID'
        AWS_SECRET_KEY = 'AWS_SECRET_ACCESS_KEY'
    )
    FILE_FORMAT = RAW.JSON_FORMAT;

LIST @RAW.WEATHER_S3_STAGE;

COPY INTO RAW.WEATHER_OBSERVATIONS (
    raw_data,
    source_file,
    loaded_at
)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @RAW.WEATHER_S3_STAGE
)
FILE_FORMAT = RAW.JSON_FORMAT
ON_ERROR = CONTINUE;
